cni/cni-plugins-windows-amd64-c74e0e996.tgz:
  size: 9678154
  object_id: da0e8048-675b-4701-68e9-7db89e88723b
  sha: 02c4d67a17a28c26cc471e56bf01dcacd104b346
flannel-v0.11.0-23-gfab9f202-dirty-windows-amd64.tar.gz:
  size: 9557878
  object_id: d36a1560-90e0-43bb-72e3-03ca92195820
  sha: 0509c2e58b23a13515115cec6be0f1102b1ad1df
flannel-v0.11.0-windows-amd64.tar.gz:
  size: 9488010
  object_id: 968eac5f-3008-4bcf-5481-f3f4179162d4
  sha: 71cb61a487c40df8eeb4d2bd68d7e891b51b44bb
kubernetes-windows-1.14.1/kube-proxy.exe:
  size: 39756800
  object_id: 14ed28de-b0a9-441a-4358-8ad43b1502aa
  sha: 799fee6969430e82147b4c5ec119ff33af3de5ac
kubernetes-windows-1.14.1/kubectl.exe:
  size: 43559424
  object_id: 878892cc-e09e-4d5b-4835-f8fca9798b99
  sha: 8583b3f65b9e3cb0053a51c2145ca4bd9a330f9d
kubernetes-windows-1.14.1/kubelet.exe:
  size: 116621312
  object_id: ab37fc74-826a-4567-419d-4657c286f21f
  sha: d19d5dbd98fdd238d033ad7047630bda473eaf64
